package com.example.b2scbsamples

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.view.View
import android.widget.Button
import android.widget.ImageView
import android.widget.TextView
import androidx.constraintlayout.widget.ConstraintLayout
import com.example.b2scbsamples.model.Dice
import com.google.android.material.snackbar.Snackbar

//R is a autogenerated file for the resources
//R.java has names and autogenerated hexa nos for each resource

class MainActivity : AppCompatActivity() {

    //val TAG = "MainActivity"
    val TAG = MainActivity::class.java.simpleName
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)  //inflating the layout xml
        val rollButton: Button = findViewById(R.id.btnRoll)
        Log.i(TAG,"activity created")

        rollButton.setOnClickListener {
        Log.e(TAG,"button was clicked")
            rollDice()
        }

    }


    /**
     * this method will set the random no on the textview
     */
    private fun rollDice() {
        Log.w(TAG,"dice was rolled")
        val myDice = Dice(6)
        val rollNoTv : TextView = findViewById(R.id.tvRollno)
        val diceRoll = myDice.roll()
        rollNoTv.text = diceRoll.toString()
        Log.v(TAG, "got the results")
        val diceImage : ImageView = findViewById(R.id.ivDice)
        Log.d(TAG,"setting the image for no"+diceRoll)

        val drawableResource = when (diceRoll) {
            1 -> R.drawable.dice_1
            2 -> R.drawable.dice_2
            3 -> R.drawable.dice_3
            4 -> R.drawable.dice_4
            5 -> R.drawable.dice_5
           // 6 -> R.drawable.dice_6
            else -> {R.drawable.dice_6}
        }

        diceImage.setImageResource(drawableResource)
    }


    fun inflating(){
        val textView = TextView(this)
        textView.text = "happy android coding"
        textView.textSize = 32.0f
    }
}